Repository mkrumholz/relational_rails, pull requests merged in 2021-05, with the labels that each got.

#18 Create Plot Show and Index pages
  Gemfile
  Gemfile.lock
  app/controllers/plots_controller.rb
  app/models/garden.rb
  app/models/plot.rb
  app/views/gardens/show.html.erb
  app/views/layouts/application.html.erb
  app/views/plots/index.html.erb
  app/views/plots/show.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  coverage/.resultset.json
  coverage/index.html
  db/migrate/20210511201021_create_plot.rb
  db/migrate/20210511202200_add_gardens_to_plots.rb
  db/schema.rb
  db/seeds.rb
  spec/models/garden_spec.rb
  spec/models/plot_spec.rb
  spec/rails_helper.rb
Labels: CRUD, enhancement, iteration 1

#19 Gem updates (adding feature testing gems)
  .gitignore
  Gemfile
  Gemfile.lock
  coverage/.resultset.json
  coverage/assets/0.12.3/DataTables-1.10.20/images/sort_asc.png
  coverage/assets/0.12.3/DataTables-1.10.20/images/sort_asc_disabled.png
  coverage/assets/0.12.3/DataTables-1.10.20/images/sort_both.png
  coverage/assets/0.12.3/DataTables-1.10.20/images/sort_desc.png
  coverage/assets/0.12.3/DataTables-1.10.20/images/sort_desc_disabled.png
  coverage/assets/0.12.3/application.css
  coverage/assets/0.12.3/application.js
  coverage/assets/0.12.3/colorbox/border.png
  coverage/assets/0.12.3/colorbox/controls.png
  coverage/assets/0.12.3/colorbox/loading.gif
  coverage/assets/0.12.3/colorbox/loading_background.png
  coverage/assets/0.12.3/favicon_green.png
  coverage/assets/0.12.3/favicon_red.png
  coverage/assets/0.12.3/favicon_yellow.png
  coverage/assets/0.12.3/images/ui-bg_flat_0_aaaaaa_40x100.png
  coverage/assets/0.12.3/images/ui-bg_flat_75_ffffff_40x100.png
  coverage/assets/0.12.3/images/ui-bg_glass_55_fbf9ee_1x400.png
  coverage/assets/0.12.3/images/ui-bg_glass_65_ffffff_1x400.png
  coverage/assets/0.12.3/images/ui-bg_glass_75_dadada_1x400.png
  coverage/assets/0.12.3/images/ui-bg_glass_75_e6e6e6_1x400.png
  coverage/assets/0.12.3/images/ui-bg_glass_95_fef1ec_1x400.png
  coverage/assets/0.12.3/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  coverage/assets/0.12.3/images/ui-icons_222222_256x240.png
  coverage/assets/0.12.3/images/ui-icons_2e83ff_256x240.png
  coverage/assets/0.12.3/images/ui-icons_454545_256x240.png
  coverage/assets/0.12.3/images/ui-icons_888888_256x240.png
  coverage/assets/0.12.3/images/ui-icons_cd0a0a_256x240.png
  coverage/assets/0.12.3/loading.gif
  coverage/assets/0.12.3/magnify.png
  coverage/index.html
  spec/models/plot_spec.rb
  spec/rails_helper.rb
Labels: bug, enhancement

#29 Complete Iteration 1 for Gardens/Plots
  .gitignore
  app/assets/stylesheets/application.css
  app/controllers/garden_plots_controller.rb
  app/controllers/gardens_controller.rb
  app/models/garden.rb
  app/views/garden_plots/index.html.erb
  app/views/gardens/index.html.erb
  app/views/gardens/show.html.erb
  config/routes.rb
  coverage/.last_run.json
  db/seeds.rb
  spec/features/gardens/index_spec.rb
  spec/features/gardens/plots/index_spec.rb
  spec/features/gardens/show_spec.rb
Labels: ActiveRecord, iteration 1, usability

#38 Feature/flower shop index
  app/controllers/flower_shops_controller.rb
  app/controllers/flowers_controller.rb
  app/models/flower.rb
  app/views/flower_shops/index.html.erb
  app/views/flower_shops/show.html.erb
  app/views/flowers/index.html.erb
  config/routes.rb
  db/migrate/20210515155523_create_flowers.rb
  db/schema.rb
  spec/features/flower_shops/index_spec.rb
  spec/features/flowers/index_spec.rb
Labels: CRUD, enhancement, iteration 1

#46 Create and Update functionality for gardens
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.css
  app/controllers/gardens_controller.rb
  app/views/gardens/edit.html.erb
  app/views/gardens/index.html.erb
  app/views/gardens/new.html.erb
  app/views/gardens/show.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  spec/features/gardens/edit_spec.rb
  spec/features/gardens/index_spec.rb
  spec/features/gardens/new_spec.rb
  spec/features/gardens/show_spec.rb
Labels: CRUD, enhancement, iteration 2

#47 Add Create and Delete functionality for Garden Plots
  app/controllers/garden_plots_controller.rb
  app/controllers/gardens_controller.rb
  app/controllers/plots_controller.rb
  app/views/garden_plots/index.html.erb
  app/views/garden_plots/new.html.erb
  app/views/plots/edit.html.erb
  app/views/plots/index.html.erb
  app/views/plots/show.html.erb
  config/routes.rb
  spec/features/gardens/index_spec.rb
  spec/features/gardens/plots/index_spec.rb
  spec/features/gardens/plots/new_spec.rb
  spec/features/plots/edit_spec.rb
  spec/features/plots/index_spec.rb
  spec/features/plots/show_spec.rb
  spec/models/garden_spec.rb
Labels: CRUD, enhancement, iteration 2

#58 Test coverage
  spec/features/flowers/index_spec.rb
  spec/models/flower_shop_spec.rb
Labels: iteration 1, refactoring

#63 Add delete functionality
  app/controllers/gardens_controller.rb
  app/controllers/plots_controller.rb
  app/models/garden.rb
  app/views/gardens/index.html.erb
  app/views/gardens/show.html.erb
  app/views/plots/index.html.erb
  app/views/plots/show.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  spec/features/gardens/index_spec.rb
  spec/features/gardens/show_spec.rb
  spec/features/plots/index_spec.rb
  spec/features/plots/show_spec.rb
  spec/models/garden_spec.rb
Labels: CRUD, enhancement, iteration 3

#68 Feature/flower it2
  app/controllers/flower_shop_flowers_controller.rb
  app/controllers/flower_shops_controller.rb
  app/controllers/flowers_controller.rb
  app/models/flower_shop.rb
  app/views/flower_shop_flowers/index.html.erb
  app/views/flower_shop_flowers/new.html.erb
  app/views/flower_shops/edit.html.erb
  app/views/flower_shops/index.html.erb
  app/views/flower_shops/new.html.erb
  app/views/flower_shops/show.html.erb
  app/views/flowers/edit.html.erb
  app/views/flowers/show.html.erb
  config/routes.rb
  spec/features/flower_shops/edit_spec.rb
  spec/features/flower_shops/flowers/index_spec.rb
  spec/features/flower_shops/flowers/new_spec.rb
  spec/features/flower_shops/index_spec.rb
  spec/features/flower_shops/new_spec.rb
  spec/features/flower_shops/show_spec.rb
  spec/features/flowers/edit_spec.rb
  spec/features/flowers/index_spec.rb
  spec/features/flowers/show_spec.rb
  spec/models/flower_shop_spec.rb
Labels: ActiveRecord, CRUD, enhancement, iteration 2, usability

#77 Update formatting for consistency
  app/assets/stylesheets/application.css
  app/views/flower_shop_flowers/index.html.erb
  app/views/flower_shop_flowers/new.html.erb
  app/views/flower_shops/edit.html.erb
  app/views/flower_shops/index.html.erb
  app/views/flower_shops/new.html.erb
  app/views/flower_shops/show.html.erb
  app/views/flowers/edit.html.erb
  app/views/flowers/index.html.erb
  app/views/flowers/show.html.erb
Labels: enhancement
